name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: GitSSHGroup
  - group: ApiKeys
  - group: OctoDefault
  - name: solutionFile
    value: 'Octo.CommunicationOperator.sln'
  - name: artifactsFrameworkVersion
    value: 'net9.0'
  - name: buildConfiguration
    value: 'Release'
  - name: buildPlatform
    value: 'Any CPU'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}    

stages:
 - stage: Build
   jobs:
     - job: local_build
       displayName: "Build nuget and execute tests"
       pool:
         name: Gerald-Local-Linux
       steps:
         - template: update-build-number.yml
         - checkout: self
           clean: true
         - template: set-version.yml
         - template: download-ca.yml           
         - task: DotNetCoreCLI@2
           displayName: 'Test'
           inputs:
             command: 'test'
             projects: |
               '**/*Tests.csproj'
               !'**/*SystemTests.csproj'
             testRunTitle: 'CI'
         - template: build-and-push-docker-image.yml
           parameters:
             ContainerRegistry: $(DockerRegistryPublicConnection)
             Repository: meshmakers/octo-communication-operator
             Dockerfile: src/CommunicationOperator/Dockerfile
             Architecture: 'linux/arm64,linux/amd64'
             PrivateRegistry: $(DockerRegistryPrivateUri)             
         - template: handle-artifacts.yml

     

