name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: GitSSHGroup
  - group: ApiKeys
  - group: OctoDefault
  - name: solutionFile
    value: 'Octo.CommunicationController.sln'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}

stages:
 - stage: Build
   jobs:
     - job: local_build
       displayName: "Build nuget and execute tests"
       pool:
         name: Gerald-Local-Linux
       steps:
         - checkout: self
           clean: true
           submodules: true
         - task: PowerShell@2
           inputs:
             targetType: 'inline'
             script: |
               Write-Host "Source Branch $(Build.SourceBranch)"
               Write-Host "Source Branch Name $(Build.SourceBranchName)"
               $branch = '$(Build.SourceBranch)'
               $branchName = '$(Build.SourceBranchName)'
               if ($branch.StartsWith("refs/tags/r")) {
                 $major = [int]$branchName.Split(".")[0].substring(1)
                 $minor = [int]$branchName.Split(".")[1]
                 $revision = [int]$branchName.Split(".")[2]
                 $buildNumber = "$major.$minor.$revision.0"
                 Write-Host "##vso[task.setvariable variable=MajorVersion;]$major"
                 Write-Host "##vso[task.setvariable variable=MinorVersion;]$minor"
                 Write-Host "Setting build number to $buildNumber"
                 Write-Host "##vso[build.updatebuildnumber]$buildNumber"
               }
           displayName: 'Set build number'
         - template: setversion.yml
         - template: download-ca.yml           
         - task: PowerShell@2
           displayName: "Enable multiarch support"
           inputs:
             targetType: 'inline'
             script: |
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
         - task: DotNetCoreCLI@2
           displayName: 'Test'
           inputs:
             command: 'test'
             projects: |
               '**/*Tests.csproj'
               !'**/*SystemTests.csproj'
             testRunTitle: 'CI'
         - template: build-and-push-docker-image.yml
           parameters:
             Repository: meshmakers/octo-communication-operator
             Dockerfile: src/CommunicationOperator/DockerfileArm64v8
             IsRelease: ${{ variables.isRelease }}
             Architecture: 'arm64v8'
         - template: build-and-push-docker-image.yml
           parameters:
             Repository: meshmakers/octo-communication-operator
             Dockerfile: src/CommunicationOperator/Dockerfile
             IsRelease: ${{ variables.isRelease }}
             Architecture: 'amd64'
         - task: PowerShell@2
           displayName: 'Create versioninfo file'
           inputs:
             targetType: 'inline'
             script: |
               New-Item $(build.artifactstagingdirectory)/versioninfo.txt
               Set-Content $(build.artifactstagingdirectory)/versioninfo.txt $(Build.BuildNumber)
         - task: PublishBuildArtifacts@1
           displayName: 'Publish Artifact: local'
           inputs:
             ArtifactName: local
     

