apiVersion: octo-mesh.meshmakers.io/v1alpha1
kind: CommunicationPool
metadata:
  name: first-pool
spec:
  communicationControllerUri: "https://192.168.102.147:5015"
  poolName: "k8sfirmianstrasse"
  tenantId: "meshtest"
  brokerHost: "192.168.102.147"
  ignoreCertificateValidation: true
