<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Meshmakers.Octo.Communication.Operator.Tests</RootNamespace>
        <AssemblyName>Meshmakers.Octo.Communication.Operator.Tests</AssemblyName>
        <IsPackable>false</IsPackable>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
        <Configurations>Debug;Release;DebugL</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
      <PackageReference Include="NSubstitute" Version="6.2.0" />
      <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.17">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="TUnit" Version="1.65.63" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\CommunicationOperator\CommunicationOperator.csproj" />
    </ItemGroup>

</Project>
