apiVersion: octo-mesh.meshmakers.io/v1alpha1
kind: PlugPool
metadata:
  name: demo-plug-pool
spec:
  plugControllerUri: "https://plugs.staging.meshmakers.cloud"
  plugPoolName: "k8sfirmianstrasse"
  tenantId: "meshtest"
  brokerHost: "mq.staging.meshmakers.cloud"
  
