apiVersion: octo-mesh.meshmakers.io/v1alpha1
kind: CommunicationPool
metadata:
  name: first-pool
spec:
  communicationControllerUri: "https://localhost:5015"
  poolName: "k8sfirmianstrasse"
  tenantId: "meshtest"
  brokerHost: "localhost"
  
